### ISSUE TITLE
Can't find a way to use static domain by Python

### ISSUE THREAD

**Issue by BabakAmini** [ngrok/ngrok-python#49] opened 2023-09-10 12:24 UTC
Contrary to what has been said [here](https://github.com/ngrok/ngrok-python#full-configuration), there is no ‍`domain` parameter in the `ngrok.connect()` method. The function declaration seems to be changed, so how can I use my static domain obtained from https://dashboard.ngrok.com/cloud-edge/domains?

**Comment by russorat** [comment] 2023-09-11 13:34
hi @BabakAmini , thanks for the issue. I'm able to use the domain parameter in the example found here: https://github.com/ngrok/ngrok-python/blob/main/examples/ngrok-connect-full.py

do you mind pasting your code and the specific error you are seeing so that we can reproduce?

**Comment by bobzilladev** [comment] 2023-09-21 00:04
Hello @BabakAmini, it looks like the code here is using the community [pyngrok](https://github.com/alexdlaird/pyngrok) library, not the one from [this repo](https://github.com/ngrok/ngrok-python). For instance, this line is importing from `pyngrok`:
```
from pyngrok import ngrok, conf
```

If you want to use the library from this repo you can `python -m pip install ngrok` to install it, and then `import ngrok` to start using it in the code. This library has a similar `connect` call which can be made, but does so without running a separate agent process.

As far as the error, does it occur when hitting the service directly (not going through ngrok)? That looks like it may be unrelated to the ngrok connectivity.

**Comment by bobzilladev** [comment] 2023-10-03 15:17
Hello! That error with the text `for an unauthenticated client` makes it look like the authtoken is not being loaded, I suspect when the domain is not set it is running as unauthenticated rather than as a free authenticated account.

If using the `connect` function check that `authtoken_from_env=True` is set, and the authtoken from the ngrok dashboard is in the `NGROK_AUTHTOKEN` environment variable. Or alternatively you can set the authtoken directly with `authtoken="<token>"`. We can look into adding some more logging around whether an authtoken was used or not for session creation.

**Comment by bobzilladev** [comment] 2023-10-03 15:34
Ah, the `authtoken` option doesn't have an underscore in the middle, so that property isn't being used there. The full list of available options can be referenced here: https://github.com/ngrok/ngrok-python#full-configuration

**Comment by bobzilladev** [comment] 2023-10-03 16:32
I'll close this ticket out, feel free to open a new one if you run into any other issues!

**Closed by bobzilladev** 2023-10-03 16:32 UTC
